---
name: mc
version: "3"
services:
  backup:
    image: zettaio/restic-compose-backup
    restart: unless-stopped
    environment:
      RESTIC_REPOSITORY: "b2:minecraft-9a7253"
      RESTIC_PASSWORD: ${BAK_RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${BAK_B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${BAK_B2_ACCOUNT_KEY}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - cache:/cache

  router:
    image: itzg/mc-router
    restart: unless-stopped
    command: --mapping=le.mc.abcedea.net=lostera:25565 --mapping=froggrove.mc.abcedea.net=fg:25565
    ports:
      - "25565:25565"

  fg:
    image: itzg/minecraft-server
    restart: unless-stopped
    labels:
      restic-compose-backup.volumes: true
    environment:
      EULA: TRUE
      TYPE: VANILLA
      MEMORY: 4G
      VERSION: 1.19.4
    volumes:
      - game-fg_data:/data
    tty: true
    stdin_open: true

  lostera:
    image: itzg/minecraft-server:java8-multiarch
    restart: unless-stopped
    labels:
      restic-compose-backup.volumes: true
    environment:
      EULA: TRUE
      MEMORY: 8G
      TYPE: MODRINTH
      MODRINTH_MODPACK: https://modrinth.com/modpack/the-lost-era/version/1.6.4
      MODRINTH_IGNORE_MISSING_FILES: config/mcinstanceloader/pack.mcinstance
      WORLD_TYPE: BIOMESOP
    volumes:
      - game-le_data:/data
    tty: true
    stdin_open: true

volumes:
  cache:
  game-fg_data:
  game-sb3_data:
  game-le_data:
