---
name: mc
version: "3"
services:
  backup:
    image: zettaio/restic-compose-backup
    restart: unless-stopped
    environment:
      RESTIC_REPOSITORY: "b2:minecraft-9a7253"
      RESTIC_PASSWORD: ${BAK_RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${BAK_B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${BAK_B2_ACCOUNT_KEY}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - cache:/cache

  router:
    image: itzg/mc-router
    restart: unless-stopped
    command: --mapping=sb3.mc.abcedea.net=stoneblock3:25565 --mapping=froggrove.mc.abcedea.net=fg:25565
    ports:
      - "25565:25565"

  web:
    image: itzg/rcon
    restart: unless-stopped
    labels:
      restic-compose-backup.volumes: true
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: guest
      RWA_ADMIN: "TRUE"
    volumes:
      - web_data:/opt/rcon-web-admin/db
    ports:
      - "4326:4326"
      - "4327:4327"

  fg:
    image: itzg/minecraft-server
    restart: unless-stopped
    labels:
      restic-compose-backup.volumes: true
    environment:
      EULA: TRUE
      TYPE: VANILLA
      MEMORY: 4G
      VERSION: 1.19.4
    volumes:
      - game-fg_data:/data
    tty: true
    stdin_open: true

  stoneblock3:
    image: itzg/minecraft-server
    restart: unless-stopped
    labels:
      restic-compose-backup.volumes: true
    environment:
      EULA: TRUE
      TYPE: FTBA
      MEMORY: 8G
      FTB_MODPACK_ID: 100
      FTB_MODPACK_VERSION_ID: 2308
    volumes:
      - game-sb3_data:/data
    tty: true
    stdin_open: true

volumes:
  cache:
  web_data:
  game-fg_data:
  game-sb3_data:
